selmag:
  services:
    catalogue:
      uri: http://localhost:8081
      registration-id: keycloak

spring:
  datasource:
    url: jdbc:postgresql://localhost:5445/manager
    username: manager
    password: manager
  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          manager-app:
            provider: keycloack
          keycloak:
            client-id: manager-app
            client-secret: iDTUtdmK6m1Ph28SyP14cO1ST6kLkg3b
            scope:
              - openid
              - view_catalogue
              - edit_catalogue
              - microprofile-jwt